### ISSUE TITLE
LazyList.toString SOE

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#420]
```
scala> val l = LazyList.from(1 to 10000)
l: scala.collection.immutable.LazyList[Int] = LazyList(?)

scala> l.foreach(x => ())

scala> l
java.lang.StackOverflowError
  at scala.collection.immutable.LazyList$Cons.toString(LazyList.scala:480)
  at scala.collection.immutable.LazyList$Cons.toString(LazyList.scala:480)
  at scala.collection.immutable.LazyList$Cons.toString(LazyList.scala:480)
```

**Comment by lrytz** [comment]
Very funny thing:

I can reproduce this behavior when starting a new repl (with `JAVA_OPS` empty). But after running it for a few times, the JVM will inline / optimize something to make it actually work :-)

```
Welcome to Scala 2.13.0-pre-5ba8d97 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> val l = LazyList.from(1 to 10000)
l: scala.collection.immutable.LazyList[Int] = LazyList(?)

scala> l.foreach(x => ())

scala> try { l.toString; println(s"worked") } catch { case _: StackOverflowError => println(s"failed") }
failed

scala> val l = LazyList.from(1 to 10000)
l: scala.collection.immutable.LazyList[Int] = LazyList(?)

scala> l.foreach(x => ())

scala> try { l.toString; println(s"worked") } catch { case _: StackOverflowError => println(s"failed") }
failed

scala> val l = LazyList.from(1 to 10000)
l: scala.collection.immutable.LazyList[Int] = LazyList(?)

scala> l.foreach(x => ())

scala> try { l.toString; println(s"worked") } catch { case _: StackOverflowError => println(s"failed") }
failed

scala> val l = LazyList.from(1 to 10000)
l: scala.collection.immutable.LazyList[Int] = LazyList(?)

scala> l.foreach(x => ())

scala> try { l.toString; println(s"worked") } catch { case _: StackOverflowError => println(s"failed") }
failed

scala> val l = LazyList.from(1 to 10000)
l: scala.collection.immutable.LazyList[Int] = LazyList(?)

scala> l.foreach(x => ())

scala> try { l.toString; println(s"worked") } catch { case _: StackOverflowError => println(s"failed") }
failed

scala> val l = LazyList.from(1 to 10000)
l: scala.collection.immutable.LazyList[Int] = LazyList(?)

scala> l.foreach(x => ())

scala> try { l.toString; println(s"worked") } catch { case _: StackOverflowError => println(s"failed") }
worked
```
