### ISSUE TITLE
LazyList.flatMap SOE

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#421]
```
scala> val l = LazyList.from(1 to 10000)
l: scala.collection.immutable.LazyList[Int] = LazyList(?)

scala> l.flatMap(List(_)) == l
java.lang.StackOverflowError
  at scala.collection.Iterator$$anon$1.<init>(Iterator.scala:1150)
  at scala.collection.Iterator$.apply(Iterator.scala:1149)
  at scala.collection.View$Elems.iterator(View.scala:98)
  at scala.collection.mutable.Growable.addAll(Growable.scala:49)
  at scala.collection.mutable.Growable.addAll$(Growable.scala:48)
  at scala.collection.mutable.ListBuffer.addAll(ListBuffer.scala:34)
  at scala.collection.mutable.Growable.$plus$plus$eq(Growable.scala:57)
  at scala.collection.mutable.Growable.$plus$plus$eq$(Growable.scala:57)
  at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:34)
  at scala.collection.mutable.ListBuffer$.from(ListBuffer.scala:284)
  at scala.collection.immutable.List$.from(List.scala:436)
  at scala.collection.immutable.List$.from(List.scala:429)
  at scala.collection.IterableFactoryLike.apply(Factory.scala:98)
  at scala.collection.IterableFactoryLike.apply$(Factory.scala:98)
  at scala.collection.immutable.List$.apply(List.scala:432)
  at .$anonfun$res0$1(<console>:1)
  at .$anonfun$res0$1$adapted(<console>:1)
  at scala.collection.immutable.LazyListOps.flatMap(LazyList.scala:347)
  at scala.collection.immutable.LazyListOps.flatMap$(LazyList.scala:342)
  at scala.collection.immutable.LazyList.flatMap(LazyList.scala:186)
  at scala.collection.immutable.LazyListOps.$anonfun$flatMap$1(LazyList.scala:355)
  at scala.collection.immutable.LazyListOps.lazyAppendAll(LazyList.scala:249)
  at scala.collection.immutable.LazyListOps.lazyAppendAll$(LazyList.scala:248)
  at scala.collection.immutable.LazyList.lazyAppendAll(LazyList.scala:186)
  at scala.collection.immutable.LazyListOps.$anonfun$lazyAppendAll$2(LazyList.scala:249)
  at scala.collection.immutable.LazyList$Cons.tail$lzycompute(LazyList.scala:476)
  at scala.collection.immutable.LazyList$Cons.tail(LazyList.scala:474)
  at scala.collection.immutable.LazyList$Cons.tail(LazyList.scala:466)
  at scala.collection.LinearSeqOps$$anon$1.next(LinearSeq.scala:25)
  at scala.collection.immutable.LazyList$.evaluatedElem$lzycompute$1(LazyList.scala:529)
  at scala.collection.immutable.LazyList$.evaluatedElem$1(LazyList.scala:529)
```

works in 2.12 Stream.

**Comment by optician** [comment]
@lrytz I guess it was fixed in #454 but also #469 was created.
```
scala> val l: LazyList[Int] = LazyList.from(Iterator.range(1,1000000))
l: strawman.collection.immutable.LazyList[Int] = LazyList(?)

scala> l.flatMap(List(_)) == l
res10: Boolean = true
```
