### ISSUE TITLE
Allow offline mode with Dotty

### ISSUE THREAD

**Issue by szeiger** [scala/collection-strawman#92]
sbt offline mode is currently broken because of the way we resolve Dotty:

```
$ sbt -offline
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024M; support was removed in 8.0
[info] Loading global plugins from /Users/szeiger/.sbt/0.13/plugins/project
[info] Loading global plugins from /Users/szeiger/.sbt/0.13/plugins
[info] Loading project definition from /Users/szeiger/code/collection-strawman/project
Fetching latest Dotty nightly version (requires an internet connection)...
java.net.UnknownHostException: repo1.maven.org
       	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
       	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
       	at java.net.Socket.connect(Socket.java:589)
       	at java.net.Socket.connect(Socket.java:538)
       	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
       	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
       	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
       	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
       	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
       	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
       	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
       	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
       	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:989)
       	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:987)
       	at java.security.AccessController.doPrivileged(Native Method)
       	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
       	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:986)
       	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
       	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
       	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
       	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1433)
       	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
       	at java.security.AccessController.doPrivileged(Native Method)
       	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
       	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1430)
       	at java.net.URL.openStream(URL.java:1045)
       	at scala.io.Source$.fromURL(Source.scala:140)
       	at scala.io.Source$.fromURL(Source.scala:130)
       	at com.felixmulder.dotty.plugin.DottyPlugin$autoImport$.dottyLatestNightlyBuild(DottyPlugin.scala:18)
       	at $54d02c4975ea6c60a7d6$$anonfun$$sbtdef$1.apply(/Users/szeiger/code/collection-strawman/build.sbt:3)
       	at $54d02c4975ea6c60a7d6$$anonfun$$sbtdef$1.apply(/Users/szeiger/code/collection-strawman/build.sbt:3)
       	at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:609)
       	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
       	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
       	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
       	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
       	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
       	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
       	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)
```

**Comment by julienrf** [comment]
This is not anymore an issue since we use a fixed version of Dotty.
